config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'statements#index'

  resources :expenditures, only: %i[create destroy]
  resources :incomes, only: %i[create destroy]
  resources :statements

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/statement_concern.rb
# frozen_string_literal: true

module StatementConcern
  extend ActiveSupport::Concern

  def total_income
    incomes.sum(:amount_pennies)
  end

  def total_expenditure
    expenditures.sum(:amount_pennies)
  end

  def disposable_income
    (total_income - total_expenditure)
  end

  def rating
    total_income.positive? ? (total_expenditure / total_income.to_f).round(2) : 0
  end

  def grade
    case rating
    when 0..0.1
      'A'
    when 0.1..0.3
      'B'
    when 0.3..0.5
      'C'
    else
      'D'
    end
  end
end

app/models/expenditure.rb
# frozen_string_literal: true

class Expenditure < ApplicationRecord
  belongs_to :statement
end

app/models/income.rb
# frozen_string_literal: true

class Income < ApplicationRecord
  belongs_to :statement
end

app/models/statement.rb
# frozen_string_literal: true

class Statement < ApplicationRecord
  include ::StatementConcern

  belongs_to :user
  has_many :incomes, dependent: :destroy
  has_many :expenditures, dependent: :destroy

  validates :name, presence: true
  validates :user_id, presence: true

  def incomes_attributes=(attributes)
    attributes.each_value do |income_attributes|
      next unless income_attributes[:name].present? && income_attributes[:amount_pennies].present?

      income_attributes[:amount_pennies] = income_attributes[:amount_pennies].to_i * 100
      incomes.build(income_attributes)
    end
  end

  def expenditures_attributes=(attributes)
    attributes.each_value do |expenditure_attributes|
      next unless expenditure_attributes[:name].present? && expenditure_attributes[:amount_pennies].present?

      expenditure_attributes[:amount_pennies] = expenditure_attributes[:amount_pennies].to_i * 100
      expenditures.build(expenditure_attributes)
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :statements, dependent: :destroy
  has_many :incomes, through: :statements
  has_many :expenditures, through: :statements
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  require 'pry'
end

app/controllers/statements_controller.rb
# frozen_string_literal: true

class StatementsController < ApplicationController
  def index
    @statements = Statement.where(user_id: current_user.id)
    @statement = current_user.statements.build
  end

  def show
    @statement = Statement.find(params[:id])
    @expenditures = @statement.expenditures
    @incomes = @statement.incomes
  end

  def new
    @statement = current_user.statements.build
    5.times do
      @incomes = @statement.incomes.build
      @expenditures = @statement.expenditures.build
    end
  end

  def create
    @statement = current_user.statements.new(statement_params)

    respond_to do |format|
      if @statement.save
        format.html { redirect_to statements_url, notice: 'Statement successfully created.' }
        format.json { render :index, status: :created }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @statement.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @statement = Statement.find(params[:id])
    @statement.destroy!

    respond_to do |format|
      format.html { redirect_to statements_url, notice: 'Statement successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private

  def statement_params
    params.require(:statement).permit(:name, incomes_attributes: %i[name amount_pennies],
                                             expenditures_attributes: %i[name amount_pennies])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/statements_helper.rb
# frozen_string_literal: true

module StatementsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StatementGenerator</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <div style= "display: flex; justify-content: space-between">
        <h2>StatementGenerator</h2>
        <div style="color: white"><%= button_to "Sign out", destroy_user_session_path, method: :delete %></div>
      </div>
    </header>
    <%= yield %>
  </body>
</html>

app/views/statements/index.html.erb
<% if @statements.empty? %>
  <p>You don't have any statements yet!</p>
  <p class="p-3"><%= link_to 'Create your first Statement', new_statement_path %></p>
<% else %>
  <h2>Your statements</h2>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Disposable income</th>
        <th>I&E rating</th>
        <th>Grade</th>
      </tr>
    </thead>

    <tbody>
      <% @statements.each do |statement| %>
        <tr>
          <td><%= statement.name %></td>
          <td>£<%= statement.disposable_income / 100 %></td>
          <td><%= statement.rating %></td>
          <td><%= statement.grade %></td>
          <td><%= button_to 'Show', statement, method: :get %>
          <%= button_to 'Delete', statement, method: :delete, form: {data: {turbo_confirm: 'Are you sure?'}} %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <p class="p-3"><%= link_to 'New Statement', new_statement_path %></p>
<% end %>

app/views/statements/new.html.erb
<%= form_for @statement do |form| %>
  <div class="my-3 g-3">
    <%= form.label :name, style: "display: block", class: "form-label" %>
    <%= form.text_field :name, placeholder: "January", class: "form-control", required: true %>
  </div>
  
  <hr class="my-4">
  <div class="row g-3">
    <h4>Income</h4>
    <%= form.fields_for :incomes do |income_form| %>
      <div style= "display: flex">
        <div id='fields' style= "display: flex">
          <div class="col-sm-6 p-1"> 
            <%= income_form.text_field :name, placeholder: "Type", class: "form-control" %>
          </div>
          <div class="col-sm-6 p-1"> 
            <%= income_form.number_field :amount_pennies, placeholder: "Amount", class: "form-control"  %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  
  <hr class="my-4">
  <div class="row g-3">
    <h4>Expenditures</h4>
    <%= form.fields_for :expenditures do |expenditure_form| %>
      <div style= "display: flex">
        <div id='fields' style= "display: flex">
          <div class="col-sm-6 p-1"> 
            <%= expenditure_form.text_field :name, placeholder: "Type", class: "form-control" %>
          </div>
          <div class="col-sm-6 p-1"> 
            <%= expenditure_form.number_field :amount_pennies, placeholder: "Amount", class: "form-control"  %>
          </div>
        </div>
      </div>
    <% end %>
    </div>  
  </div>

  <hr class="my-4">
    <p><%= form.submit class: "w-100 btn-lg" %></p>
    <p><%= link_to 'Back', statements_path %></p>
  </div>
<% end %>

app/views/statements/show.html.erb
<h2><%= @statement.name %></h2>
  <h4>Incomes</h4>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Amount</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @incomes.each do |income| %>
        <tr>
          <td><%= income.name %></td>
          <td>£<%= income.amount_pennies / 100 %></td>
          <td><%= button_to 'Delete', income, method: :delete, form: { data: { turbo_confirm: 'Are you sure?' } } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <h4>Expenditures</h4>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Amount</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @expenditures.each do |expenditure| %>
        <tr>
          <td><%= expenditure.name %></td>
          <td>£<%= expenditure.amount_pennies / 100 %></td>
          <td><%= button_to 'Delete', expenditure, method: :delete, form: { data: { turbo_confirm: 'Are you sure?' } } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <hr class="my-4">
    <p><%= link_to 'Back', statements_path %></p>
  </div>